//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.21 at 02:15:27 PM NOVT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://fit.nsu.ru/people", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.nsu.fit.people;
