//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.21 at 02:15:27 PM NOVT 
//


package ru.nsu.fit.people;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for person-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="person-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="wife" type="{http://fit.nsu.ru/people}person-reference-type" minOccurs="0"/&gt;
 *         &lt;element name="husband" type="{http://fit.nsu.ru/people}person-reference-type" minOccurs="0"/&gt;
 *         &lt;element name="mother" type="{http://fit.nsu.ru/people}person-reference-type" minOccurs="0"/&gt;
 *         &lt;element name="father" type="{http://fit.nsu.ru/people}person-reference-type" minOccurs="0"/&gt;
 *         &lt;element name="sister" type="{http://fit.nsu.ru/people}person-reference-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="brother" type="{http://fit.nsu.ru/people}person-reference-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="son" type="{http://fit.nsu.ru/people}person-reference-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="daughter" type="{http://fit.nsu.ru/people}person-reference-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute name="person-firstname" use="required" type="{http://fit.nsu.ru/people}person-firstname-type" /&gt;
 *       &lt;attribute name="person-surname" use="required" type="{http://fit.nsu.ru/people}person-surname-type" /&gt;
 *       &lt;attribute name="person-gender" use="required" type="{http://fit.nsu.ru/people}person-gender-type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "person-type", propOrder = {
    "wife",
    "husband",
    "mother",
    "father",
    "sister",
    "brother",
    "son",
    "daughter"
})
public class PersonType {

    protected PersonReferenceType wife;
    protected PersonReferenceType husband;
    protected PersonReferenceType mother;
    protected PersonReferenceType father;
    protected List<PersonReferenceType> sister;
    protected List<PersonReferenceType> brother;
    protected List<PersonReferenceType> son;
    protected List<PersonReferenceType> daughter;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "person-firstname", required = true)
    protected String personFirstname;
    @XmlAttribute(name = "person-surname", required = true)
    protected String personSurname;
    @XmlAttribute(name = "person-gender", required = true)
    protected PersonGenderType personGender;

    /**
     * Gets the value of the wife property.
     * 
     * @return
     *     possible object is
     *     {@link PersonReferenceType }
     *     
     */
    public PersonReferenceType getWife() {
        return wife;
    }

    /**
     * Sets the value of the wife property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonReferenceType }
     *     
     */
    public void setWife(PersonReferenceType value) {
        this.wife = value;
    }

    /**
     * Gets the value of the husband property.
     * 
     * @return
     *     possible object is
     *     {@link PersonReferenceType }
     *     
     */
    public PersonReferenceType getHusband() {
        return husband;
    }

    /**
     * Sets the value of the husband property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonReferenceType }
     *     
     */
    public void setHusband(PersonReferenceType value) {
        this.husband = value;
    }

    /**
     * Gets the value of the mother property.
     * 
     * @return
     *     possible object is
     *     {@link PersonReferenceType }
     *     
     */
    public PersonReferenceType getMother() {
        return mother;
    }

    /**
     * Sets the value of the mother property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonReferenceType }
     *     
     */
    public void setMother(PersonReferenceType value) {
        this.mother = value;
    }

    /**
     * Gets the value of the father property.
     * 
     * @return
     *     possible object is
     *     {@link PersonReferenceType }
     *     
     */
    public PersonReferenceType getFather() {
        return father;
    }

    /**
     * Sets the value of the father property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonReferenceType }
     *     
     */
    public void setFather(PersonReferenceType value) {
        this.father = value;
    }

    /**
     * Gets the value of the sister property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the sister property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSister().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonReferenceType }
     * 
     * 
     */
    public List<PersonReferenceType> getSister() {
        if (sister == null) {
            sister = new ArrayList<PersonReferenceType>();
        }
        return this.sister;
    }

    /**
     * Gets the value of the brother property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the brother property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBrother().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonReferenceType }
     * 
     * 
     */
    public List<PersonReferenceType> getBrother() {
        if (brother == null) {
            brother = new ArrayList<PersonReferenceType>();
        }
        return this.brother;
    }

    /**
     * Gets the value of the son property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the son property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonReferenceType }
     * 
     * 
     */
    public List<PersonReferenceType> getSon() {
        if (son == null) {
            son = new ArrayList<PersonReferenceType>();
        }
        return this.son;
    }

    /**
     * Gets the value of the daughter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the daughter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDaughter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonReferenceType }
     * 
     * 
     */
    public List<PersonReferenceType> getDaughter() {
        if (daughter == null) {
            daughter = new ArrayList<PersonReferenceType>();
        }
        return this.daughter;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the personFirstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonFirstname() {
        return personFirstname;
    }

    /**
     * Sets the value of the personFirstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonFirstname(String value) {
        this.personFirstname = value;
    }

    /**
     * Gets the value of the personSurname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonSurname() {
        return personSurname;
    }

    /**
     * Sets the value of the personSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonSurname(String value) {
        this.personSurname = value;
    }

    /**
     * Gets the value of the personGender property.
     * 
     * @return
     *     possible object is
     *     {@link PersonGenderType }
     *     
     */
    public PersonGenderType getPersonGender() {
        return personGender;
    }

    /**
     * Sets the value of the personGender property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonGenderType }
     *     
     */
    public void setPersonGender(PersonGenderType value) {
        this.personGender = value;
    }

}
